/**
 * Utility function to convert RouteObject to URL string
 */

// Import types (these will be generated by core.ts)
export type RouteObject<S extends Record<string, string> = Record<string, string>, H extends string = string> = {
  pathname: never;
  params?: Record<string, string>;
  search?: S;
  hash?: H;
}; // Placeholder - actual type will come from core.ts

/**
 * Check if a value is a RouteObject
 */
export function isRouteObject(value: unknown): value is RouteObject {
  return (
    typeof value === 'object' && value !== null && 'pathname' in value && typeof (value as any).pathname === 'string'
  );
}

/**
 * Convert RouteObject to URL string
 *
 * @example
 * routes({
 *   pathname: '/blog/[slug]',
 *   params: { slug: 'hello' },
 *   search: { page: '1' },
 *   hash: 'section-1'
 * }) // returns '/blog/hello?page=1#section-1'
 */
export function routes<S extends Record<string, string> = Record<string, string>, H extends string = string>(
  route: RouteObject<S, H>,
): string {
  let url = route.pathname as string;

  // Replace dynamic parameters
  if ('params' in route && route.params) {
    Object.entries(route.params).forEach(([key, value]) => {
      url = url.replace(`[${key}]`, String(value));
    });
  }

  // Add search params
  if (route.search && Object.keys(route.search).length > 0) {
    const searchParams = new URLSearchParams(route.search as Record<string, string>);
    url += `?${searchParams.toString()}`;
  }

  // Add hash
  if (route.hash) {
    url += `#${route.hash}`;
  }

  return url;
}
