coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

flags:
web:
  paths:
    paths:
      - apps/web/src/
    carryforward: true
  nextjs-routes:
    paths:
      - packages/nextjs-routes/
    carryforward: true
  mdx-handler:
    paths:
      - packages/mdx-handler/
    carryforward: true
