export type CurrencyCode =
  | 'KRW' // 한국
  | 'USD' // 미국
  | 'JPY' // 일본
  | 'EUR' // 유럽
  | 'CNY' // 중국
  | 'THB' // 태국
  | 'HKD' // 홍콩
  | 'TWD' // 대만
  | 'VND' // 베트남
  | 'IDR' // 인도네시아
  | 'PHP' // 필리핀
  | 'SGD' // 싱가포르
  | 'MYR' // 말레이시아
  | 'AUD' // 오스트레일리아
  | 'CAD' // 캐나다
  | 'NZD' // 뉴질랜드
  | 'DKK' // 덴마크
  | 'GBP' // 영국
  | 'CHF'; // 스위스
