import { ROUTER, type RouterName } from '@/core/config';

import * as fs from 'fs';
import matter from 'gray-matter';
import * as path from 'path';

type ContentSection = Extract<RouterName, 'blog' | 'projects' | 'libraries'>;
const CONTENT_SECTIONS: ContentSection[] = ['blog', 'projects', 'libraries'];

interface ContentEntry {
  slug: string;
  filePath: string; // MDX 파일 경로
  metadata: Record<string, unknown>; // MDX 파일의 frontmatter
}

/**
 * 콘텐츠 디렉토리를 스캔하여 모든 .mdx 파일 찾기
 */
function discoverContent(section: ContentSection): ContentEntry[] {
  const viewsDir = path.join(process.cwd(), 'src', 'views', section);
  const entries: ContentEntry[] = [];

  if (!fs.existsSync(viewsDir)) {
    console.warn(`⚠️  Warning: Views directory not found: ${viewsDir}`);
    return entries;
  }

  function scan(dir: string, relativePath: string = '') {
    const items = fs.readdirSync(dir, { withFileTypes: true });

    for (const item of items) {
      const fullPath = path.join(dir, item.name);
      const itemRelativePath = relativePath ? path.join(relativePath, item.name) : item.name;

      if (item.isDirectory()) {
        // 폴더 내부 스캔
        scan(fullPath, itemRelativePath);
      } else if (item.name === 'index.mdx') {
        // {slug}/index.mdx 패턴
        const slug = relativePath || item.name.replace(/\.mdx$/, '');
        const fileContent = fs.readFileSync(fullPath, 'utf-8');
        const { data } = matter(fileContent);
        entries.push({
          slug,
          filePath: fullPath,
          metadata: data,
        });
      } else if (item.name.endsWith('.mdx') && !relativePath) {
        // 루트 레벨의 단일 파일
        const slug = item.name.replace(/\.mdx$/, '');
        const fileContent = fs.readFileSync(fullPath, 'utf-8');
        const { data } = matter(fileContent);
        entries.push({
          slug,
          filePath: fullPath,
          metadata: data,
        });
      }
    }
  }

  scan(viewsDir);
  return entries;
}

/**
 * 섹션명을 PascalCase로 변환
 */
function toPascalCase(section: ContentSection): string {
  const map: Record<ContentSection, string> = {
    blog: 'Blog',
    projects: 'Project',
    libraries: 'Library',
  };
  return map[section];
}

/**
 * 카테고리 타입명 생성
 */
function getCategoryType(section: ContentSection): string {
  const map: Record<ContentSection, string> = {
    blog: 'BlogCategory',
    projects: 'ProjectCategory',
    libraries: 'LibraryCategory',
  };
  return map[section];
}

/**
 * 엔티티 폴더명으로 변환 (views는 복수형, entities는 단수형)
 */
function getEntityFolderName(section: ContentSection): string {
  const map: Record<ContentSection, string> = {
    blog: 'blog',
    projects: 'project',
    libraries: 'library',
  };
  return map[section];
}

/**
 * 레지스트리 파일 생성
 */
function generateRegistry(section: ContentSection) {
  const entries = discoverContent(section);

  if (entries.length === 0) {
    console.warn(`⚠️  Warning: No content found for section: ${section}`);
    return;
  }

  const pascalSection = toPascalCase(section);
  const categoryType = getCategoryType(section);
  const typeName = pascalSection;

  // 배열 항목 생성
  const arrayItems = entries
    .map(entry => {
      const metadataStr = JSON.stringify(entry.metadata, null, 4)
        .split('\n')
        .map((line, i) => (i === 0 ? line : `    ${line}`))
        .join('\n');
      // Windows 경로의 백슬래시를 슬래시로 변경
      const normalizedPath = entry.filePath.replace(/\\/g, '/');
      return `  {
    slug: '${entry.slug}',
    ...${metadataStr},
    filePath: '${normalizedPath}',
    path: '${ROUTER[section]}/${entry.slug}',
  }`;
    })
    .join(',\n');

  // 카테고리 필터 함수명
  const filterFunctionName = `get${pascalSection}ListByCategory`;
  const registryName = `${section}Registry`;

  // TypeScript 코드 생성
  const code = `// THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY
// Generated by scripts/generate-content-registry.ts

import type { ${typeName} } from './types';
import type { ${categoryType} } from '@/core/types';

export const ${registryName}: ${typeName}[] = [
${arrayItems}
];

/**
 * 카테고리로 콘텐츠 필터링
 */
export function ${filterFunctionName}(category: ${categoryType}): ${typeName}[] {
  return ${registryName}.filter(item => item.category.includes(category));
}
`;

  // 출력 경로 설정
  const entityFolder = getEntityFolderName(section);
  const outputPath = path.join(process.cwd(), 'src', 'entities', entityFolder, 'registry.generated.ts');

  // 파일 쓰기
  fs.writeFileSync(outputPath, code, 'utf-8');

  console.log(
    `✅ Generated ${section} registry: ${entries.length} ${entries.length === 1 ? 'entry' : 'entries'} (MDX)`,
  );
}

/**
 * 모든 섹션 레지스트리 생성
 */
function generateAllRegistries() {
  console.log('🔧 Generating content registries...\n');

  CONTENT_SECTIONS.forEach(section => {
    try {
      generateRegistry(section);
    } catch (error) {
      console.error(`❌ Error generating registry for ${section}:`, error);
      process.exit(1);
    }
  });

  console.log('\n✨ All registries generated successfully!');
}

// 스크립트 실행
generateAllRegistries();
