import * as fs from 'fs';
import * as path from 'path';

type ContentSection = 'blog' | 'portfolio' | 'projects' | 'libraries';

interface ContentEntry {
  slug: string;
  importPath: string;
}

/**
 * 콘텐츠 디렉토리를 스캔하여 모든 .tsx 파일 찾기
 */
function discoverContent(section: ContentSection): ContentEntry[] {
  const viewsDir = path.join(process.cwd(), 'src', 'views', section);
  const entries: ContentEntry[] = [];

  if (!fs.existsSync(viewsDir)) {
    console.warn(`⚠️  Warning: Views directory not found: ${viewsDir}`);
    return entries;
  }

  function scan(dir: string, relativePath: string = '') {
    const items = fs.readdirSync(dir, { withFileTypes: true });

    for (const item of items) {
      const fullPath = path.join(dir, item.name);
      const itemRelativePath = relativePath
        ? path.join(relativePath, item.name)
        : item.name;

      if (item.isDirectory()) {
        // 폴더 내부 스캔
        scan(fullPath, itemRelativePath);
      } else if (item.name === 'index.tsx') {
        // {slug}/index.tsx 패턴 (기본 방식)
        const slug = relativePath || item.name.replace('.tsx', '');
        entries.push({
          slug,
          importPath: `@/views/${section}/${slug}`,
        });
      } else if (item.name.endsWith('.tsx') && !relativePath) {
        // 루트 레벨의 단일 .tsx 파일 (지원)
        const slug = item.name.replace('.tsx', '');
        entries.push({
          slug,
          importPath: `@/views/${section}/${slug}`,
        });
      }
    }
  }

  scan(viewsDir);
  return entries;
}

/**
 * 섹션명을 PascalCase로 변환
 */
function toPascalCase(section: ContentSection): string {
  const map: Record<ContentSection, string> = {
    blog: 'Blog',
    portfolio: 'Portfolio',
    projects: 'Project',
    libraries: 'Library',
  };
  return map[section];
}

/**
 * 카테고리 타입명 생성
 */
function getCategoryType(section: ContentSection): string {
  const map: Record<ContentSection, string> = {
    blog: 'BlogCategory',
    portfolio: 'PortfolioCategory',
    projects: 'ProjectCategory',
    libraries: 'LibraryCategory',
  };
  return map[section];
}

/**
 * 엔티티 폴더명으로 변환 (views는 복수형, entities는 단수형)
 */
function getEntityFolderName(section: ContentSection): string {
  const map: Record<ContentSection, string> = {
    blog: 'blog',
    portfolio: 'portfolio',
    projects: 'project',
    libraries: 'library',
  };
  return map[section];
}

/**
 * 레지스트리 파일 생성
 */
function generateRegistry(section: ContentSection) {
  const entries = discoverContent(section);

  if (entries.length === 0) {
    console.warn(
      `⚠️  Warning: No content found for section: ${section}`
    );
    return;
  }

  const pascalSection = toPascalCase(section);
  const categoryType = getCategoryType(section);
  const typeName = pascalSection;

  // Import 문 생성
  const imports = entries
    .map(
      (entry, idx) =>
        `import Content${idx}, { metadata as meta${idx} } from '${entry.importPath}';`
    )
    .join('\n');

  // 배열 항목 생성
  const arrayItems = entries
    .map(
      (entry, idx) => `  {
    slug: '${entry.slug}',
    ...meta${idx},
    Component: Content${idx},
  }`
    )
    .join(',\n');

  // 카테고리 필터 함수명
  const filterFunctionName = `get${pascalSection}ListByCategory`;
  const registryName = `${section}Registry`;

  // TypeScript 코드 생성
  const code = `// THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY
// Generated by scripts/generate-content-registry.ts

import type { ${typeName} } from './types';
import type { ${categoryType} } from '@/core/types/metadata';

${imports}

export const ${registryName}: ${typeName}[] = [
${arrayItems}
];

/**
 * 카테고리로 콘텐츠 필터링
 */
export function ${filterFunctionName}(category: ${categoryType}): ${typeName}[] {
  return ${registryName}.filter(item => item.category.includes(category));
}
`;

  // 출력 경로 설정
  const entityFolder = getEntityFolderName(section);
  const outputPath = path.join(
    process.cwd(),
    'src',
    'entities',
    entityFolder,
    'registry.generated.ts'
  );

  // 파일 쓰기
  fs.writeFileSync(outputPath, code, 'utf-8');
  console.log(
    `✅ Generated ${section} registry: ${entries.length} ${entries.length === 1 ? 'entry' : 'entries'}`
  );
}

/**
 * 모든 섹션 레지스트리 생성
 */
function generateAllRegistries() {
  console.log('🔧 Generating content registries...\n');

  const sections: ContentSection[] = [
    'blog',
    'portfolio',
    'projects',
    'libraries',
  ];

  sections.forEach(section => {
    try {
      generateRegistry(section);
    } catch (error) {
      console.error(`❌ Error generating registry for ${section}:`, error);
      process.exit(1);
    }
  });

  console.log('\n✨ All registries generated successfully!');
}

// 스크립트 실행
generateAllRegistries();
