// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Generated by @jinho-blog/nextjs-routes

/**
 * Static route pathnames (no dynamic parameters)
 */
export type StaticPathname =
  | '/'
  | '/api/blog'
  | '/api/libraries'
  | '/api/libraries/category'
  | '/api/projects'
  | '/blog'
  | '/libraries'
  | '/projects'
  | '/rss.xml';

/**
 * Dynamic route pathnames (with parameters like [slug])
 */
export type DynamicPathname =
  | '/api/blog/[slug]'
  | '/api/blog/[slug]/content'
  | '/api/libraries/[slug]'
  | '/api/libraries/[slug]/content'
  | '/api/projects/[slug]'
  | '/api/projects/[slug]/content'
  | '/blog/[slug]'
  | '/libraries/[slug]'
  | '/projects/[slug]';

/**
 * All route pathnames
 */
export type Pathname = StaticPathname | DynamicPathname;

/**
 * Path parameters for dynamic routes
 * Maps each DynamicPathname to its required parameters
 *
 * @example
 * PathParams<'/blog/[slug]'> = { slug: string }
 * PathParams<'/blog/[slug]/[id]'> = { slug: string; id: string }
 */
export type PathParams<P extends DynamicPathname> = P extends '/api/blog/[slug]'
  ? { slug: string }
  : P extends '/api/blog/[slug]/content'
    ? { slug: string }
    : P extends '/api/libraries/[slug]'
      ? { slug: string }
      : P extends '/api/libraries/[slug]/content'
        ? { slug: string }
        : P extends '/api/projects/[slug]'
          ? { slug: string }
          : P extends '/api/projects/[slug]/content'
            ? { slug: string }
            : P extends '/blog/[slug]'
              ? { slug: string }
              : P extends '/libraries/[slug]'
                ? { slug: string }
                : P extends '/projects/[slug]'
                  ? { slug: string }
                  : never;

/**
 * Search/query parameters (customizable via generic)
 *
 * @example
 * SearchParams<{ page: string; count: string }>
 */
export type SearchParams<T = Record<string, string | string[] | undefined>> = T;

/**
 * Hash parameter (customizable via generic)
 *
 * @example
 * HashParam<'section-1' | 'section-2'>
 */
export type HashParam<T = string> = T;

/**
 * Route object for type-safe navigation
 * Supports both static and dynamic routes with optional search params and hash
 *
 * @example
 * // Static route
 * { pathname: '/blog', search: { page: '1' }, hash: 'section-1' }
 *
 * // Dynamic route
 * { pathname: '/blog/[slug]', params: { slug: 'hello' }, search: { page: '1' } }
 */
export type RouteObject<
  S extends Record<string, string | string[] | undefined> = Record<string, string | string[] | undefined>,
  H extends string = string,
> =
  | {
      pathname: StaticPathname;
      search?: SearchParams<S>;
      hash?: HashParam<H>;
    }
  | {
      pathname: DynamicPathname;
      params: PathParams<DynamicPathname>;
      search?: SearchParams<S>;
      hash?: HashParam<H>;
    };

declare module '@jinho-blog/nextjs-routes' {
  export type { DynamicPathname, HashParam, Pathname, PathParams, RouteObject, SearchParams, StaticPathname };

  export function isRouteObject<
    S extends Record<string, string | string[] | undefined> = Record<string, string | string[] | undefined>,
    H extends string = string,
  >(value: unknown): value is RouteObject<S, H>;

  export function routes<
    S extends Record<string, string | string[] | undefined> = Record<string, string | string[] | undefined>,
    H extends string = string,
  >(route: RouteObject<S, H>): string;
}

declare module 'next/navigation' {
  export * from 'next/navigation';

  import type { DynamicPathname, PathParams } from '@jinho-blog/nextjs-routes';
  import type { ReadonlyURLSearchParams } from 'next/navigation';

  // useParams overloads
  export function useParams(): { [key: string]: string | string[] };
  export function useParams<P extends DynamicPathname>(): PathParams<P>;

  // useSearchParams overloads
  interface TypedURLSearchParams<S extends Record<string, string | string[] | undefined>> {
    get<K extends keyof S>(name: K): S[K] | null;
    getAll<K extends keyof S>(name: K): S[K][];
    has<K extends keyof S>(name: K): boolean;
    keys(): IterableIterator<keyof S>;
    values(): IterableIterator<S[keyof S]>;
    entries(): IterableIterator<[keyof S, S[keyof S]]>;
    forEach(callback: <K extends keyof S>(value: S[K], key: K) => void): void;
    [Symbol.iterator](): IterableIterator<[keyof S, S[keyof S]]>;
    readonly size: number;
  }

  export function useSearchParams(): ReadonlyURLSearchParams;
  export function useSearchParams<S extends Record<string, string | string[] | undefined>>(): TypedURLSearchParams<S>;
}
