// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Generated by @jinho-blog/nextjs-routes

/**
 * Static route pathnames (no dynamic parameters)
 */
export type StaticPathname = '/' | '/api/blog' | '/api/libraries' | '/api/projects' | '/blog' | '/libraries' | '/projects';

/**
 * Dynamic route pathnames (with parameters like [slug])
 */
export type DynamicPathname = '/api/blog/[slug]' | '/api/blog/[slug]/content' | '/api/libraries/[slug]' | '/api/libraries/[slug]/content' | '/api/projects/[slug]' | '/api/projects/[slug]/content' | '/blog/[slug]' | '/libraries/[slug]' | '/projects/[slug]';

/**
 * Path parameters for dynamic routes
 * Maps each DynamicPathname to its required parameters
 *
 * @example
 * PathParams<'/blog/[slug]'> = { slug: string }
 * PathParams<'/blog/[slug]/[id]'> = { slug: string; id: string }
 */
export type PathParams<P extends DynamicPathname> =
  P extends '/api/blog/[slug]' ? { slug: string } :
  P extends '/api/blog/[slug]/content' ? { slug: string } :
  P extends '/api/libraries/[slug]' ? { slug: string } :
  P extends '/api/libraries/[slug]/content' ? { slug: string } :
  P extends '/api/projects/[slug]' ? { slug: string } :
  P extends '/api/projects/[slug]/content' ? { slug: string } :
  P extends '/blog/[slug]' ? { slug: string } :
  P extends '/libraries/[slug]' ? { slug: string } :
  P extends '/projects/[slug]' ? { slug: string } :
  never;

/**
 * Search/query parameters (customizable via generic)
 *
 * @example
 * SearchParams<{ page: string; limit: string }>
 */
export type SearchParams<T = Record<string, string>> = T;

/**
 * Hash parameter (customizable via generic)
 *
 * @example
 * HashParam<'section-1' | 'section-2'>
 */
export type HashParam<T = string> = T;
