export { CATEGORIES, type Category, CATEGORY_MAP } from './internal/categories';
export {
  AUTHOR_NAME,
  AUTHOR_SAME_AS,
  DEFAULT_OG_IMAGE,
  OG_IMAGE_HEIGHT,
  OG_IMAGE_WIDTH,
  PLACEHOLDER_SITE_URL,
  POSTS_PER_PAGE,
  SITE_DESCRIPTION,
  SITE_INDEXABLE,
  SITE_KEYWORDS,
  SITE_LANGUAGE,
  SITE_LOCALE,
  SITE_NAME,
  SITE_URL,
} from './internal/site';
